<?php return array(
    'root' => array(
        'name' => 'drupal/recommended-project',
        'pretty_version' => 'dev-main',
        'version' => 'dev-main',
        'reference' => '4e37d90b7508b72cd3476dc81dd5d18b7fdefb73',
        'type' => 'project',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        'asm89/stack-cors' => array(
            'pretty_version' => 'v2.3.0',
            'version' => '2.3.0.0',
            'reference' => 'acf3142e6c5eafa378dc8ef3c069ab4558993f70',
            'type' => 'library',
            'install_path' => __DIR__ . '/../asm89/stack-cors',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'chi-teck/drupal-code-generator' => array(
            'pretty_version' => '4.2.0',
            'version' => '4.2.0.0',
            'reference' => '984dd69522b5839976df51470a00a51616a21f42',
            'type' => 'library',
            'install_path' => __DIR__ . '/../chi-teck/drupal-code-generator',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'commerceguys/addressing' => array(
            'pretty_version' => 'v2.2.4',
            'version' => '2.2.4.0',
            'reference' => 'ea826dbe5b3fe76960073a2167d5cf996c811cda',
            'type' => 'library',
            'install_path' => __DIR__ . '/../commerceguys/addressing',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'commerceguys/intl' => array(
            'pretty_version' => 'v2.0.7',
            'version' => '2.0.7.0',
            'reference' => '2cf8f74987095aedff45249ce6fc7b0427beefee',
            'type' => 'library',
            'install_path' => __DIR__ . '/../commerceguys/intl',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'composer/installers' => array(
            'pretty_version' => 'v2.3.0',
            'version' => '2.3.0.0',
            'reference' => '12fb2dfe5e16183de69e784a7b84046c43d97e8e',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/./installers',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'composer/pcre' => array(
            'pretty_version' => '3.3.2',
            'version' => '3.3.2.0',
            'reference' => 'b2bed4734f0cc156ee1fe9c0da2550420d99a21e',
            'type' => 'library',
            'install_path' => __DIR__ . '/./pcre',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'composer/semver' => array(
            'pretty_version' => '3.4.4',
            'version' => '3.4.4.0',
            'reference' => '198166618906cb2de69b95d7d47e5fa8aa1b2b95',
            'type' => 'library',
            'install_path' => __DIR__ . '/./semver',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'composer/xdebug-handler' => array(
            'pretty_version' => '3.0.5',
            'version' => '3.0.5.0',
            'reference' => '6c1925561632e83d60a44492e0b344cf48ab85ef',
            'type' => 'library',
            'install_path' => __DIR__ . '/./xdebug-handler',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'consolidation/annotated-command' => array(
            'pretty_version' => '4.10.4',
            'version' => '4.10.4.0',
            'reference' => '69d29da4acac31a43caa4cea13b6b948f4e5c56d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../consolidation/annotated-command',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'consolidation/config' => array(
            'pretty_version' => '3.2.0',
            'version' => '3.2.0.0',
            'reference' => '797652cd5ac870f02eb3ca1a7169d3dbbe6e5f84',
            'type' => 'library',
            'install_path' => __DIR__ . '/../consolidation/config',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'consolidation/filter-via-dot-access-data' => array(
            'pretty_version' => '2.0.3',
            'version' => '2.0.3.0',
            'reference' => 'f9e84bc623d420120028a50dcb9b1d4609ae3b5f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../consolidation/filter-via-dot-access-data',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'consolidation/log' => array(
            'pretty_version' => '3.1.1',
            'version' => '3.1.1.0',
            'reference' => 'c1a87a94c01957697ec347fd67404d7f0030d1aa',
            'type' => 'library',
            'install_path' => __DIR__ . '/../consolidation/log',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'consolidation/output-formatters' => array(
            'pretty_version' => '4.7.0',
            'version' => '4.7.0.0',
            'reference' => 'dfc464c4d4a47594cac5eac01ce265e04b70cb94',
            'type' => 'library',
            'install_path' => __DIR__ . '/../consolidation/output-formatters',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'consolidation/robo' => array(
            'pretty_version' => '5.1.1',
            'version' => '5.1.1.0',
            'reference' => '6d02c7d800b5e1a3a8977ae74d23bce723486025',
            'type' => 'library',
            'install_path' => __DIR__ . '/../consolidation/robo',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'consolidation/site-alias' => array(
            'pretty_version' => '4.1.2',
            'version' => '4.1.2.0',
            'reference' => 'd92058201fc8475a33fb9a2b80ffe5c89472f5af',
            'type' => 'library',
            'install_path' => __DIR__ . '/../consolidation/site-alias',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'consolidation/site-process' => array(
            'pretty_version' => '5.4.2',
            'version' => '5.4.2.0',
            'reference' => 'e7fafc40ebfddc1a5ee99ee66e5d186fc1bed4da',
            'type' => 'library',
            'install_path' => __DIR__ . '/../consolidation/site-process',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'dealerdirect/phpcodesniffer-composer-installer' => array(
            'pretty_version' => 'v1.2.0',
            'version' => '1.2.0.0',
            'reference' => '845eb62303d2ca9b289ef216356568ccc075ffd1',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/../dealerdirect/phpcodesniffer-composer-installer',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'dflydev/dot-access-data' => array(
            'pretty_version' => 'v3.0.3',
            'version' => '3.0.3.0',
            'reference' => 'a23a2bf4f31d3518f3ecb38660c95715dfead60f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../dflydev/dot-access-data',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/annotations' => array(
            'pretty_version' => '2.0.2',
            'version' => '2.0.2.0',
            'reference' => '901c2ee5d26eb64ff43c47976e114bf00843acf7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/annotations',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/collections' => array(
            'pretty_version' => '2.4.0',
            'version' => '2.4.0.0',
            'reference' => '9acfeea2e8666536edff3d77c531261c63680160',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/collections',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/deprecations' => array(
            'pretty_version' => '1.1.5',
            'version' => '1.1.5.0',
            'reference' => '459c2f5dd3d6a4633d3b5f46ee2b1c40f57d3f38',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/deprecations',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/lexer' => array(
            'pretty_version' => '2.1.1',
            'version' => '2.1.1.0',
            'reference' => '861c870e8b75f7c8f69c146c7f89cc1c0f1b49b6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/lexer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'dompdf/dompdf' => array(
            'pretty_version' => 'v3.1.4',
            'version' => '3.1.4.0',
            'reference' => 'db712c90c5b9868df3600e64e68da62e78a34623',
            'type' => 'library',
            'install_path' => __DIR__ . '/../dompdf/dompdf',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'dompdf/php-font-lib' => array(
            'pretty_version' => '1.0.1',
            'version' => '1.0.1.0',
            'reference' => '6137b7d4232b7f16c882c75e4ca3991dbcf6fe2d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../dompdf/php-font-lib',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'dompdf/php-svg-lib' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'reference' => 'eb045e518185298eb6ff8d80d0d0c6b17aecd9af',
            'type' => 'library',
            'install_path' => __DIR__ . '/../dompdf/php-svg-lib',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/address' => array(
            'pretty_version' => '2.0.4',
            'version' => '2.0.4.0',
            'reference' => '2.0.4',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../web/modules/contrib/address',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/admin_toolbar' => array(
            'pretty_version' => '3.6.2',
            'version' => '3.6.2.0',
            'reference' => '3.6.2',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../web/modules/contrib/admin_toolbar',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/bootstrap5' => array(
            'pretty_version' => '4.0.6',
            'version' => '4.0.6.0',
            'reference' => '4.0.6',
            'type' => 'drupal-theme',
            'install_path' => __DIR__ . '/../../web/themes/contrib/bootstrap5',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/bootstrap5_admin' => array(
            'pretty_version' => '1.1.38',
            'version' => '1.1.38.0',
            'reference' => '1.1.38',
            'type' => 'drupal-theme',
            'install_path' => __DIR__ . '/../../web/themes/contrib/bootstrap5_admin',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/classy' => array(
            'pretty_version' => '2.0.0',
            'version' => '2.0.0.0',
            'reference' => '2.0.0',
            'type' => 'drupal-theme',
            'install_path' => __DIR__ . '/../../web/themes/contrib/classy',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/coder' => array(
            'pretty_version' => '8.3.31',
            'version' => '8.3.31.0',
            'reference' => '07c14cf2217c2b53cc4469e2ed360141e6bb18ea',
            'type' => 'phpcodesniffer-standard',
            'install_path' => __DIR__ . '/../drupal/coder',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'drupal/commerce' => array(
            'pretty_version' => '3.2.0',
            'version' => '3.2.0.0',
            'reference' => '3.2.0',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../web/modules/contrib/commerce',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/commerce_number_pattern' => array(
            'pretty_version' => '3.2.0',
            'version' => '3.2.0.0',
            'reference' => null,
            'type' => 'metapackage',
            'install_path' => null,
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/commerce_order' => array(
            'pretty_version' => '3.2.0',
            'version' => '3.2.0.0',
            'reference' => null,
            'type' => 'metapackage',
            'install_path' => null,
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/commerce_payment' => array(
            'pretty_version' => '3.2.0',
            'version' => '3.2.0.0',
            'reference' => null,
            'type' => 'metapackage',
            'install_path' => null,
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/commerce_paypal' => array(
            'pretty_version' => '2.0.0',
            'version' => '2.0.0.0',
            'reference' => '2.0.0',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../web/modules/contrib/commerce_paypal',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/commerce_price' => array(
            'pretty_version' => '3.2.0',
            'version' => '3.2.0.0',
            'reference' => null,
            'type' => 'metapackage',
            'install_path' => null,
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/commerce_store' => array(
            'pretty_version' => '3.2.0',
            'version' => '3.2.0.0',
            'reference' => null,
            'type' => 'metapackage',
            'install_path' => null,
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/commerce_stripe' => array(
            'pretty_version' => '1.3.0',
            'version' => '1.3.0.0',
            'reference' => '8.x-1.3',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../web/modules/contrib/commerce_stripe',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/conditional_fields' => array(
            'pretty_version' => '4.0.0-alpha6',
            'version' => '4.0.0.0-alpha6',
            'reference' => '4.0.0-alpha6',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../web/modules/contrib/conditional_fields',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/core' => array(
            'pretty_version' => '11.2.9',
            'version' => '11.2.9.0',
            'reference' => '31bb7212f663c09833f85fa730e58eea48705f55',
            'type' => 'drupal-core',
            'install_path' => __DIR__ . '/../../web/core',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/core-annotation' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '11.2.9',
            ),
        ),
        'drupal/core-assertion' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '11.2.9',
            ),
        ),
        'drupal/core-class-finder' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '11.2.9',
            ),
        ),
        'drupal/core-composer-scaffold' => array(
            'pretty_version' => '11.2.9',
            'version' => '11.2.9.0',
            'reference' => '891b4615c479e17245c81571c9be0156be4b03f8',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/../drupal/core-composer-scaffold',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/core-datetime' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '11.2.9',
            ),
        ),
        'drupal/core-dependency-injection' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '11.2.9',
            ),
        ),
        'drupal/core-diff' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '11.2.9',
            ),
        ),
        'drupal/core-discovery' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '11.2.9',
            ),
        ),
        'drupal/core-event-dispatcher' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '11.2.9',
            ),
        ),
        'drupal/core-file-cache' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '11.2.9',
            ),
        ),
        'drupal/core-file-security' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '11.2.9',
            ),
        ),
        'drupal/core-filesystem' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '11.2.9',
            ),
        ),
        'drupal/core-front-matter' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '11.2.9',
            ),
        ),
        'drupal/core-gettext' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '11.2.9',
            ),
        ),
        'drupal/core-graph' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '11.2.9',
            ),
        ),
        'drupal/core-http-foundation' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '11.2.9',
            ),
        ),
        'drupal/core-php-storage' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '11.2.9',
            ),
        ),
        'drupal/core-plugin' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '11.2.9',
            ),
        ),
        'drupal/core-project-message' => array(
            'pretty_version' => '11.2.9',
            'version' => '11.2.9.0',
            'reference' => '656efa00f296415ed6be2ff366ef67ae2725d7d6',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/../drupal/core-project-message',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/core-proxy-builder' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '11.2.9',
            ),
        ),
        'drupal/core-recipe-unpack' => array(
            'pretty_version' => '11.2.8',
            'version' => '11.2.8.0',
            'reference' => '7a48dd030f613f0154cb65d3ad68ee95d56383e8',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/../drupal/core-recipe-unpack',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/core-recommended' => array(
            'pretty_version' => '11.2.9',
            'version' => '11.2.9.0',
            'reference' => '05ad85164d1a7700f931a34ed69bb83ea0d615b1',
            'type' => 'metapackage',
            'install_path' => null,
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/core-render' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '11.2.9',
            ),
        ),
        'drupal/core-serialization' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '11.2.9',
            ),
        ),
        'drupal/core-transliteration' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '11.2.9',
            ),
        ),
        'drupal/core-utility' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '11.2.9',
            ),
        ),
        'drupal/core-uuid' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '11.2.9',
            ),
        ),
        'drupal/core-version' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '11.2.9',
            ),
        ),
        'drupal/crop' => array(
            'pretty_version' => '2.5.0',
            'version' => '2.5.0.0',
            'reference' => '8.x-2.5',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../web/modules/contrib/crop',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/ctools' => array(
            'pretty_version' => '4.1.0',
            'version' => '4.1.0.0',
            'reference' => '4.1.0',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../web/modules/contrib/ctools',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/entity' => array(
            'pretty_version' => '1.6.0',
            'version' => '1.6.0.0',
            'reference' => '8.x-1.6',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../web/modules/contrib/entity',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/entity_reference_revisions' => array(
            'pretty_version' => '1.12.0',
            'version' => '1.12.0.0',
            'reference' => '8.x-1.12',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../web/modules/contrib/entity_reference_revisions',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/field_group' => array(
            'pretty_version' => '4.0.0',
            'version' => '4.0.0.0',
            'reference' => '4.0.0',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../web/modules/contrib/field_group',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/flag' => array(
            'pretty_version' => '5.0.3',
            'version' => '5.0.3.0',
            'reference' => '5.0.3',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../web/modules/contrib/flag',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/focal_point' => array(
            'pretty_version' => '2.1.2',
            'version' => '2.1.2.0',
            'reference' => '2.1.2',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../web/modules/contrib/focal_point',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/fullcalendar_view' => array(
            'pretty_version' => '5.2.5',
            'version' => '5.2.5.0',
            'reference' => '5.2.5',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../web/modules/contrib/fullcalendar_view',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/gin' => array(
            'pretty_version' => '5.0.9',
            'version' => '5.0.9.0',
            'reference' => '5.0.9',
            'type' => 'drupal-theme',
            'install_path' => __DIR__ . '/../../web/themes/contrib/gin',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/gin_login' => array(
            'pretty_version' => 'dev-2.1.x',
            'version' => 'dev-2.1.x',
            'reference' => '19d640a959c7ab6201b8e16c6a2eae37781e0fe9',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../web/modules/contrib/gin_login',
            'aliases' => array(
                0 => '2.1.x-dev',
            ),
            'dev_requirement' => false,
        ),
        'drupal/gin_toolbar' => array(
            'pretty_version' => '3.0.2',
            'version' => '3.0.2.0',
            'reference' => '3.0.2',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../web/modules/contrib/gin_toolbar',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/honeypot' => array(
            'pretty_version' => '2.2.2',
            'version' => '2.2.2.0',
            'reference' => '2.2.2',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../web/modules/contrib/honeypot',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/image_widget_crop' => array(
            'pretty_version' => '3.0.0',
            'version' => '3.0.0.0',
            'reference' => '3.0.0',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../web/modules/contrib/image_widget_crop',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/inline_entity_form' => array(
            'pretty_version' => '3.0.0-rc21',
            'version' => '3.0.0.0-RC21',
            'reference' => '3.0.0-rc21',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../web/modules/contrib/inline_entity_form',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/menu_link_attributes' => array(
            'pretty_version' => '1.5.0',
            'version' => '1.5.0.0',
            'reference' => '8.x-1.5',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../web/modules/contrib/menu_link_attributes',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/metatag' => array(
            'pretty_version' => '2.2.0',
            'version' => '2.2.0.0',
            'reference' => '2.2.0',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../web/modules/contrib/metatag',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/migrate_plus' => array(
            'pretty_version' => '6.0.8',
            'version' => '6.0.8.0',
            'reference' => '6.0.8',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../web/modules/contrib/migrate_plus',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/migrate_tools' => array(
            'pretty_version' => '6.1.2',
            'version' => '6.1.2.0',
            'reference' => '6.1.2',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../web/modules/contrib/migrate_tools',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/paragraphs' => array(
            'pretty_version' => '1.19.0',
            'version' => '1.19.0.0',
            'reference' => '8.x-1.19',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../web/modules/contrib/paragraphs',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/pathauto' => array(
            'pretty_version' => '1.14.0',
            'version' => '1.14.0.0',
            'reference' => '8.x-1.14',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../web/modules/contrib/pathauto',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/profile' => array(
            'pretty_version' => '1.13.0',
            'version' => '1.13.0.0',
            'reference' => '8.x-1.13',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../web/modules/contrib/profile',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/rat' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'reference' => '28202b02262a39ac8dbbfd43696b67c0c8c46b71',
            'type' => 'library',
            'install_path' => __DIR__ . '/../drupal/rat',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/recommended-project' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'reference' => '4e37d90b7508b72cd3476dc81dd5d18b7fdefb73',
            'type' => 'project',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/stable' => array(
            'pretty_version' => '2.1.0',
            'version' => '2.1.0.0',
            'reference' => '2.1.0',
            'type' => 'drupal-theme',
            'install_path' => __DIR__ . '/../../web/themes/contrib/stable',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/state_machine' => array(
            'pretty_version' => '1.13.0',
            'version' => '1.13.0.0',
            'reference' => '8.x-1.13',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../web/modules/contrib/state_machine',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/token' => array(
            'pretty_version' => '1.16.0',
            'version' => '1.16.0.0',
            'reference' => '8.x-1.16',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../web/modules/contrib/token',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/twbstools' => array(
            'pretty_version' => '2.1.0',
            'version' => '2.1.0.0',
            'reference' => '2.1.0',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../web/modules/contrib/twbstools',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drupal/twig_tweak' => array(
            'pretty_version' => '3.4.1',
            'version' => '3.4.1.0',
            'reference' => '3.4.1',
            'type' => 'drupal-module',
            'install_path' => __DIR__ . '/../../web/modules/contrib/twig_tweak',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'drush/drush' => array(
            'pretty_version' => '13.7.0',
            'version' => '13.7.0.0',
            'reference' => '70de523716de1125233de17e172a38c4ecdde397',
            'type' => 'library',
            'install_path' => __DIR__ . '/../drush/drush',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'egulias/email-validator' => array(
            'pretty_version' => '4.0.4',
            'version' => '4.0.4.0',
            'reference' => 'd42c8731f0624ad6bdc8d3e5e9a4524f68801cfa',
            'type' => 'library',
            'install_path' => __DIR__ . '/../egulias/email-validator',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'firebase/php-jwt' => array(
            'pretty_version' => 'v6.11.1',
            'version' => '6.11.1.0',
            'reference' => 'd1e91ecf8c598d073d0995afa8cd5c75c6e19e66',
            'type' => 'library',
            'install_path' => __DIR__ . '/../firebase/php-jwt',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'grasmash/expander' => array(
            'pretty_version' => '3.0.1',
            'version' => '3.0.1.0',
            'reference' => 'eea11b9afb0c32483b18b9009f4ca07b770e39f4',
            'type' => 'library',
            'install_path' => __DIR__ . '/../grasmash/expander',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'grasmash/yaml-cli' => array(
            'pretty_version' => '3.2.1',
            'version' => '3.2.1.0',
            'reference' => '09a8860566958a1576cc54bbe910a03477e54971',
            'type' => 'library',
            'install_path' => __DIR__ . '/../grasmash/yaml-cli',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'guzzlehttp/guzzle' => array(
            'pretty_version' => '7.9.3',
            'version' => '7.9.3.0',
            'reference' => '7b2f29fe81dc4da0ca0ea7d42107a0845946ea77',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/guzzle',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'guzzlehttp/promises' => array(
            'pretty_version' => '2.2.0',
            'version' => '2.2.0.0',
            'reference' => '7c69f28996b0a6920945dd20b3857e499d9ca96c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/promises',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'guzzlehttp/psr7' => array(
            'pretty_version' => '2.7.1',
            'version' => '2.7.1.0',
            'reference' => 'c2270caaabe631b3b44c85f99e5a04bbb8060d16',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzlehttp/psr7',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'jangregor/phpstan-prophecy' => array(
            'pretty_version' => '1.0.2',
            'version' => '1.0.2.0',
            'reference' => '5ee56c7db1d58f0578c82a35e3c1befe840e85a9',
            'type' => 'phpstan-extension',
            'install_path' => __DIR__ . '/../jangregor/phpstan-prophecy',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'jean85/pretty-package-versions' => array(
            'pretty_version' => '2.1.1',
            'version' => '2.1.1.0',
            'reference' => '4d7aa5dab42e2a76d99559706022885de0e18e1a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../jean85/pretty-package-versions',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laravel/prompts' => array(
            'pretty_version' => 'v0.3.8',
            'version' => '0.3.8.0',
            'reference' => '096748cdfb81988f60090bbb839ce3205ace0d35',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laravel/prompts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'league/container' => array(
            'pretty_version' => '4.2.5',
            'version' => '4.2.5.0',
            'reference' => 'd3cebb0ff4685ff61c749e54b27db49319e2ec00',
            'type' => 'library',
            'install_path' => __DIR__ . '/../league/container',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'masterminds/html5' => array(
            'pretty_version' => '2.9.0',
            'version' => '2.9.0.0',
            'reference' => 'f5ac2c0b0a2eefca70b2ce32a5809992227e75a6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../masterminds/html5',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mck89/peast' => array(
            'pretty_version' => 'v1.17.4',
            'version' => '1.17.4.0',
            'reference' => 'c6a63f32410d2e4ee2cd20fe94b35af147fb852d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mck89/peast',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mglaman/drupal-check' => array(
            'pretty_version' => '1.5.0',
            'version' => '1.5.0.0',
            'reference' => '4011f1f357bdd89793d13b1f8536625eb9d3cce7',
            'type' => 'project',
            'install_path' => __DIR__ . '/../mglaman/drupal-check',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mglaman/phpstan-drupal' => array(
            'pretty_version' => '1.3.9',
            'version' => '1.3.9.0',
            'reference' => '973a4e89e19ea7dbd60af0aa939b18a873cf7f2f',
            'type' => 'phpstan-extension',
            'install_path' => __DIR__ . '/../mglaman/phpstan-drupal',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'nette/neon' => array(
            'pretty_version' => 'v3.4.6',
            'version' => '3.4.6.0',
            'reference' => '36e3f4f89fd8a7b89ada74c7a678baa9f7cc7719',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nette/neon',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'nikic/php-parser' => array(
            'pretty_version' => 'v5.6.2',
            'version' => '5.6.2.0',
            'reference' => '3a454ca033b9e06b63282ce19562e892747449bb',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nikic/php-parser',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'orno/di' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => '~2.0',
            ),
        ),
        'pear/archive_tar' => array(
            'pretty_version' => '1.5.0',
            'version' => '1.5.0.0',
            'reference' => 'b439c859564f5cbb0f64ad6002d0afe84a889602',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pear/archive_tar',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'pear/console_getopt' => array(
            'pretty_version' => 'v1.4.3',
            'version' => '1.4.3.0',
            'reference' => 'a41f8d3e668987609178c7c4a9fe48fecac53fa0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pear/console_getopt',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'pear/pear-core-minimal' => array(
            'pretty_version' => 'v1.10.16',
            'version' => '1.10.16.0',
            'reference' => 'c0f51b45f50683bf5bbf558036854ebc9b54d033',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pear/pear-core-minimal',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'pear/pear_exception' => array(
            'pretty_version' => 'v1.0.2',
            'version' => '1.0.2.0',
            'reference' => 'b14fbe2ddb0b9f94f5b24cf08783d599f776fff0',
            'type' => 'class',
            'install_path' => __DIR__ . '/../pear/pear_exception',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phootwork/collection' => array(
            'pretty_version' => 'v3.2.3',
            'version' => '3.2.3.0',
            'reference' => '46dde20420fba17766c89200bc3ff91d3e58eafa',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phootwork/collection',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phootwork/lang' => array(
            'pretty_version' => 'v3.2.3',
            'version' => '3.2.3.0',
            'reference' => '52ec8cce740ce1c424eef02f43b43d5ddfec7b5e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phootwork/lang',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'php-tuf/composer-stager' => array(
            'pretty_version' => 'v2.0.2',
            'version' => '2.0.2.0',
            'reference' => '3b8cad67352ebef1f854995efc722728518cafd8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../php-tuf/composer-stager',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phpowermove/docblock' => array(
            'pretty_version' => 'v4.0',
            'version' => '4.0.0.0',
            'reference' => 'a73f6e17b7d4e1b92ca5378c248c952c9fae7826',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpowermove/docblock',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phpstan/extension-installer' => array(
            'pretty_version' => '1.4.3',
            'version' => '1.4.3.0',
            'reference' => '85e90b3942d06b2326fba0403ec24fe912372936',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/../phpstan/extension-installer',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpstan/phpdoc-parser' => array(
            'pretty_version' => '2.3.0',
            'version' => '2.3.0.0',
            'reference' => '1e0cd5370df5dd2e556a36b9c62f62e555870495',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpstan/phpdoc-parser',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpstan/phpstan' => array(
            'pretty_version' => '1.12.32',
            'version' => '1.12.32.0',
            'reference' => '2770dcdf5078d0b0d53f94317e06affe88419aa8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpstan/phpstan',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phpstan/phpstan-deprecation-rules' => array(
            'pretty_version' => '1.2.1',
            'version' => '1.2.1.0',
            'reference' => 'f94d246cc143ec5a23da868f8f7e1393b50eaa82',
            'type' => 'phpstan-extension',
            'install_path' => __DIR__ . '/../phpstan/phpstan-deprecation-rules',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/cache' => array(
            'pretty_version' => '3.0.0',
            'version' => '3.0.0.0',
            'reference' => 'aa5030cfa5405eccfdcb1083ce040c2cb8d253bf',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/cache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/container' => array(
            'pretty_version' => '2.0.2',
            'version' => '2.0.2.0',
            'reference' => 'c71ecc56dfe541dbd90c5360474fbc405f8d5963',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/container',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/container-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.1|2.0',
                1 => '^1.0',
            ),
        ),
        'psr/event-dispatcher' => array(
            'pretty_version' => '1.0.0',
            'version' => '1.0.0.0',
            'reference' => 'dbefd12671e8a14ec7f180cab83036ed26714bb0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/event-dispatcher',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/event-dispatcher-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/http-client' => array(
            'pretty_version' => '1.0.3',
            'version' => '1.0.3.0',
            'reference' => 'bb5906edc1c324c9a05aa0873d40117941e5fa90',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-client',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-client-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/http-factory' => array(
            'pretty_version' => '1.1.0',
            'version' => '1.1.0.0',
            'reference' => '2b4765fddfe3b508ac62f829e852b1501d3f6e8a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-factory',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-factory-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/http-message' => array(
            'pretty_version' => '2.0',
            'version' => '2.0.0.0',
            'reference' => '402d35bcb92c70c026d1a6a9883f06b2ead23d71',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/http-message',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/http-message-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0',
            ),
        ),
        'psr/log' => array(
            'pretty_version' => '3.0.2',
            'version' => '3.0.2.0',
            'reference' => 'f16e1d5863e37f8d8c2a01719f5b34baa2b714d3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/log',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/log-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0|2.0|3.0',
            ),
        ),
        'psy/psysh' => array(
            'pretty_version' => 'v0.12.15',
            'version' => '0.12.15.0',
            'reference' => '38953bc71491c838fcb6ebcbdc41ab7483cd549c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psy/psysh',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'ralouphie/getallheaders' => array(
            'pretty_version' => '3.0.3',
            'version' => '3.0.3.0',
            'reference' => '120b605dfeb996808c31b6477290a714d356e822',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ralouphie/getallheaders',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'revolt/event-loop' => array(
            'pretty_version' => 'v1.0.8',
            'version' => '1.0.8.0',
            'reference' => 'b6fc06dce8e9b523c9946138fa5e62181934f91c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../revolt/event-loop',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'rsky/pear-core-min' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v1.10.16',
            ),
        ),
        'sabberworm/php-css-parser' => array(
            'pretty_version' => 'v8.9.0',
            'version' => '8.9.0.0',
            'reference' => 'd8e916507b88e389e26d4ab03c904a082aa66bb9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sabberworm/php-css-parser',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'sainsburys/guzzle-oauth2-plugin' => array(
            'pretty_version' => 'v3.0.7',
            'version' => '3.0.7.0',
            'reference' => 'cfb96110cc7199dbde8f1c68dfe35f79a81340f6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sainsburys/guzzle-oauth2-plugin',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'sebastian/diff' => array(
            'pretty_version' => '7.0.0',
            'version' => '7.0.0.0',
            'reference' => '7ab1ea946c012266ca32390913653d844ecd085f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/diff',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'sirbrillig/phpcs-variable-analysis' => array(
            'pretty_version' => 'v2.13.0',
            'version' => '2.13.0.0',
            'reference' => 'a15e970b8a0bf64cfa5e86d941f5e6b08855f369',
            'type' => 'phpcodesniffer-standard',
            'install_path' => __DIR__ . '/../sirbrillig/phpcs-variable-analysis',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'slevomat/coding-standard' => array(
            'pretty_version' => '8.22.1',
            'version' => '8.22.1.0',
            'reference' => '1dd80bf3b93692bedb21a6623c496887fad05fec',
            'type' => 'phpcodesniffer-standard',
            'install_path' => __DIR__ . '/../slevomat/coding-standard',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'squizlabs/php_codesniffer' => array(
            'pretty_version' => '3.13.5',
            'version' => '3.13.5.0',
            'reference' => '0ca86845ce43291e8f5692c7356fccf3bcf02bf4',
            'type' => 'library',
            'install_path' => __DIR__ . '/../squizlabs/php_codesniffer',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'stripe/stripe-php' => array(
            'pretty_version' => 'v15.10.0',
            'version' => '15.10.0.0',
            'reference' => '3df1a19a33477af9ead8984dbd84e8f637c36199',
            'type' => 'library',
            'install_path' => __DIR__ . '/../stripe/stripe-php',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/console' => array(
            'pretty_version' => 'v7.3.6',
            'version' => '7.3.6.0',
            'reference' => 'c28ad91448f86c5f6d9d2c70f0cf68bf135f252a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/console',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/dependency-injection' => array(
            'pretty_version' => 'v7.3.6',
            'version' => '7.3.6.0',
            'reference' => '98af8bb46c56aedd9dd5a7f0414fc72bf2dcfe69',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/dependency-injection',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/deprecation-contracts' => array(
            'pretty_version' => 'v3.6.0',
            'version' => '3.6.0.0',
            'reference' => '63afe740e99a13ba87ec199bb07bbdee937a5b62',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/deprecation-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/error-handler' => array(
            'pretty_version' => 'v7.3.6',
            'version' => '7.3.6.0',
            'reference' => 'bbe40bfab84323d99dab491b716ff142410a92a8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/error-handler',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/event-dispatcher' => array(
            'pretty_version' => 'v7.3.3',
            'version' => '7.3.3.0',
            'reference' => 'b7dc69e71de420ac04bc9ab830cf3ffebba48191',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/event-dispatcher',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/event-dispatcher-contracts' => array(
            'pretty_version' => 'v3.6.0',
            'version' => '3.6.0.0',
            'reference' => '59eb412e93815df44f05f342958efa9f46b1e586',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/event-dispatcher-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/event-dispatcher-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '2.0|3.0',
            ),
        ),
        'symfony/filesystem' => array(
            'pretty_version' => 'v7.3.6',
            'version' => '7.3.6.0',
            'reference' => 'e9bcfd7837928ab656276fe00464092cc9e1826a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/filesystem',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/finder' => array(
            'pretty_version' => 'v7.3.5',
            'version' => '7.3.5.0',
            'reference' => '9f696d2f1e340484b4683f7853b273abff94421f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/finder',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/http-foundation' => array(
            'pretty_version' => 'v7.3.7',
            'version' => '7.3.7.0',
            'reference' => 'db488a62f98f7a81d5746f05eea63a74e55bb7c4',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/http-foundation',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/http-kernel' => array(
            'pretty_version' => 'v7.3.7',
            'version' => '7.3.7.0',
            'reference' => '10b8e9b748ea95fa4539c208e2487c435d3c87ce',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/http-kernel',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/mailer' => array(
            'pretty_version' => 'v7.3.5',
            'version' => '7.3.5.0',
            'reference' => 'fd497c45ba9c10c37864e19466b090dcb60a50ba',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/mailer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/mime' => array(
            'pretty_version' => 'v7.3.4',
            'version' => '7.3.4.0',
            'reference' => 'b1b828f69cbaf887fa835a091869e55df91d0e35',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/mime',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-ctype' => array(
            'pretty_version' => 'v1.32.0',
            'version' => '1.32.0.0',
            'reference' => 'a3cc8b044a6ea513310cbd48ef7333b384945638',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-ctype',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-iconv' => array(
            'pretty_version' => 'v1.32.0',
            'version' => '1.32.0.0',
            'reference' => '5f3b930437ae03ae5dff61269024d8ea1b3774aa',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-iconv',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-intl-grapheme' => array(
            'pretty_version' => 'v1.32.0',
            'version' => '1.32.0.0',
            'reference' => 'b9123926e3b7bc2f98c02ad54f6a4b02b91a8abe',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-grapheme',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-intl-idn' => array(
            'pretty_version' => 'v1.32.0',
            'version' => '1.32.0.0',
            'reference' => '9614ac4d8061dc257ecc64cba1b140873dce8ad3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-idn',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-intl-normalizer' => array(
            'pretty_version' => 'v1.32.0',
            'version' => '1.32.0.0',
            'reference' => '3833d7255cc303546435cb650316bff708a1c75c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-intl-normalizer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-mbstring' => array(
            'pretty_version' => 'v1.32.0',
            'version' => '1.32.0.0',
            'reference' => '6d857f4d76bd4b343eac26d6b539585d2bc56493',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-mbstring',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php81' => array(
            'pretty_version' => 'v1.33.0',
            'version' => '1.33.0.0',
            'reference' => '4a4cfc2d253c21a5ad0e53071df248ed48c6ce5c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php81',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php83' => array(
            'pretty_version' => 'v1.33.0',
            'version' => '1.33.0.0',
            'reference' => '17f6f9a6b1735c0f163024d959f700cfbc5155e5',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php83',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php84' => array(
            'pretty_version' => 'v1.32.0',
            'version' => '1.32.0.0',
            'reference' => '000df7860439609837bbe28670b0be15783b7fbf',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php84',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/process' => array(
            'pretty_version' => 'v7.3.4',
            'version' => '7.3.4.0',
            'reference' => 'f24f8f316367b30810810d4eb30c543d7003ff3b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/process',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/psr-http-message-bridge' => array(
            'pretty_version' => 'v7.3.0',
            'version' => '7.3.0.0',
            'reference' => '03f2f72319e7acaf2a9f6fcbe30ef17eec51594f',
            'type' => 'symfony-bridge',
            'install_path' => __DIR__ . '/../symfony/psr-http-message-bridge',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/routing' => array(
            'pretty_version' => 'v7.3.6',
            'version' => '7.3.6.0',
            'reference' => 'c97abe725f2a1a858deca629a6488c8fc20c3091',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/routing',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/serializer' => array(
            'pretty_version' => 'v7.3.5',
            'version' => '7.3.5.0',
            'reference' => 'ba2e50a5f2870c93f0f47ca1a4e56e4bbe274035',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/serializer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/service-contracts' => array(
            'pretty_version' => 'v3.6.1',
            'version' => '3.6.1.0',
            'reference' => '45112560a3ba2d715666a509a0bc9521d10b6c43',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/service-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/service-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.1|2.0|3.0',
            ),
        ),
        'symfony/string' => array(
            'pretty_version' => 'v7.3.4',
            'version' => '7.3.4.0',
            'reference' => 'f96476035142921000338bad71e5247fbc138872',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/string',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/translation-contracts' => array(
            'pretty_version' => 'v3.6.1',
            'version' => '3.6.1.0',
            'reference' => '65a8bc82080447fae78373aa10f8d13b38338977',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/translation-contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/validator' => array(
            'pretty_version' => 'v7.3.7',
            'version' => '7.3.7.0',
            'reference' => '8290a095497c3fe5046db21888d1f75b54ddf39d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/validator',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/var-dumper' => array(
            'pretty_version' => 'v7.3.5',
            'version' => '7.3.5.0',
            'reference' => '476c4ae17f43a9a36650c69879dcf5b1e6ae724d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/var-dumper',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/var-exporter' => array(
            'pretty_version' => 'v7.3.4',
            'version' => '7.3.4.0',
            'reference' => '0f020b544a30a7fe8ba972e53ee48a74c0bc87f4',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/var-exporter',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/yaml' => array(
            'pretty_version' => 'v7.3.5',
            'version' => '7.3.5.0',
            'reference' => '90208e2fc6f68f613eae7ca25a2458a931b1bacc',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/yaml',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'twig/twig' => array(
            'pretty_version' => 'v3.21.1',
            'version' => '3.21.1.0',
            'reference' => '285123877d4dd97dd7c11842ac5fb7e86e60d81d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../twig/twig',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'webflo/drupal-finder' => array(
            'pretty_version' => '1.3.1',
            'version' => '1.3.1.0',
            'reference' => '73045060b0894c77962a10cff047f72872d8810c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../webflo/drupal-finder',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
