<?php

declare(strict_types=1);

namespace Drupal\myeventlane_event\Form;

use Drupal\Core\Entity\EntityTypeManagerInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Session\AccountProxyInterface;
use Drupal\node\NodeInterface;

/**
 * Form alteration service for Event node forms.
 */
final class EventFormAlter {

  private EntityTypeManagerInterface $entityTypeManager;
  private AccountProxyInterface $currentUser;

  public function __construct(
    EntityTypeManagerInterface $entity_type_manager,
    AccountProxyInterface $current_user,
  ) {
    $this->entityTypeManager = $entity_type_manager;
    $this->currentUser = $current_user;
  }

  public function alterForm(array &$form, FormStateInterface $form_state): void {
    $node = $form_state->getFormObject()->getEntity();
    $is_new = $node->isNew();

    $form['#attributes']['class'][] = 'mel-event-form-vendor';

    $this->handleVendorStore($form, $form_state, $is_new);
    $this->buildEventBasics($form, $form_state);
    $this->buildDateTime($form, $form_state);
    $this->buildLocation($form, $form_state);
    $this->buildBookingConfig($form, $form_state);
    $this->buildVisibility($form, $form_state);
    $this->buildAttendeeQuestions($form, $form_state);
    $this->buildStickyFooter($form, $form_state, $node, $is_new);

    // Attach Conditional Fields library if module is enabled
    if (\Drupal::moduleHandler()->moduleExists('conditional_fields')) {
      $form['#attached']['library'][] = 'conditional_fields/conditional_fields';
    }
    
    $form['#attached']['library'][] = 'myeventlane_theme/event-form';
    $form['#attached']['library'][] = 'core/drupal.states';
    
    // Always attach location autocomplete library for event forms
    $form['#attached']['library'][] = 'myeventlane_location/address_autocomplete';
    
    // Attach location settings for JavaScript
    // Note: myeventlane_location module may have already set these with generated tokens
    // Only set defaults if not already present to avoid overwriting Apple Maps tokens
    if (!isset($form['#attached']['drupalSettings']['myeventlaneLocation'])) {
      $config = \Drupal::config('myeventlane_location.settings');
      $form['#attached']['drupalSettings']['myeventlaneLocation'] = [
        'provider' => $config->get('default_provider') ?: 'google_maps',
        'google_maps_api_key' => $config->get('google_maps_api_key') ?: '',
        'apple_maps_token' => '', // Will be generated by myeventlane_location module if needed
      ];
    } else {
      // Merge in any missing values without overwriting existing ones (especially apple_maps_token)
      $config = \Drupal::config('myeventlane_location.settings');
      $existing = &$form['#attached']['drupalSettings']['myeventlaneLocation'];
      if (!isset($existing['provider'])) {
        $existing['provider'] = $config->get('default_provider') ?: 'google_maps';
      }
      if (!isset($existing['google_maps_api_key'])) {
        $existing['google_maps_api_key'] = $config->get('google_maps_api_key') ?: '';
      }
      // Never overwrite apple_maps_token if it's already set (it's generated by MapKitTokenGenerator)
    }
  }

  private function handleVendorStore(array &$form, FormStateInterface $form_state, bool $is_new): void {
    if (isset($form['field_event_vendor'])) {
      $vendor_id = $this->getCurrentUserVendorId();
      if ($vendor_id && $is_new) {
        // Set the value in form state (uses integer ID)
        $form_state->setValue(['field_event_vendor', 0, 'target_id'], $vendor_id);
        // For hidden fields, we don't need to set #default_value on the widget
        // The form state value will be used when the form is submitted
      }
      // Hide the field completely - it's auto-populated
      $form['field_event_vendor']['#access'] = FALSE;
    }

    if (isset($form['field_event_store'])) {
      $store_id = $this->getCurrentUserStoreId();
      if ($store_id && $is_new) {
        // Set the value in form state (uses integer ID)
        $form_state->setValue(['field_event_store', 0, 'target_id'], $store_id);
        // For hidden fields, we don't need to set #default_value on the widget
        // The form state value will be used when the form is submitted
      }
      // Hide the field completely - it's auto-populated
      $form['field_event_store']['#access'] = FALSE;
    }
  }

  private function buildEventBasics(array &$form, FormStateInterface $form_state): void {
    $form['event_basics'] = [
      '#type' => 'container',
      '#attributes' => ['class' => ['mel-form-card']],
      '#weight' => -10,
    ];
    $form['event_basics']['header'] = [
      '#type' => 'container',
      '#attributes' => ['class' => ['mel-form-header']],
    ];
    $form['event_basics']['header']['title'] = [
      '#markup' => '<h2 class="mel-form-title">' . t('Event Basics') . '</h2>',
    ];
    $form['event_basics']['content'] = [
      '#type' => 'container',
      '#attributes' => ['class' => ['mel-form-content']],
    ];

    if (isset($form['title'])) {
      $form['event_basics']['content']['title'] = $form['title'];
      unset($form['title']);
    }
    if (isset($form['body'])) {
      $form['body']['widget'][0]['#attributes']['class'][] = 'mel-hide-format-help';
      $form['event_basics']['content']['body'] = $form['body'];
      unset($form['body']);
    }
    if (isset($form['field_event_image'])) {
      $form['event_basics']['content']['field_event_image'] = $form['field_event_image'];
      unset($form['field_event_image']);
    }
  }

  private function buildDateTime(array &$form, FormStateInterface $form_state): void {
    $form['date_time'] = [
      '#type' => 'container',
      '#attributes' => ['class' => ['mel-form-card']],
      '#weight' => -9,
    ];
    $form['date_time']['header'] = [
      '#type' => 'container',
      '#attributes' => ['class' => ['mel-form-header']],
    ];
    $form['date_time']['header']['title'] = [
      '#markup' => '<h2 class="mel-form-title">' . t('Date & Time') . '</h2>',
    ];
    $form['date_time']['content'] = [
      '#type' => 'container',
      '#attributes' => ['class' => ['mel-form-content']],
    ];

    if (isset($form['field_event_start'])) {
      $form['date_time']['content']['field_event_start'] = $form['field_event_start'];
      unset($form['field_event_start']);
    }
    if (isset($form['field_event_end'])) {
      $form['date_time']['content']['field_event_end'] = $form['field_event_end'];
      unset($form['field_event_end']);
    }
  }

  private function buildLocation(array &$form, FormStateInterface $form_state): void {
    $form['location'] = [
      '#type' => 'container',
      '#attributes' => ['class' => ['mel-form-card']],
      '#weight' => -8,
    ];
    $form['location']['header'] = [
      '#type' => 'container',
      '#attributes' => ['class' => ['mel-form-header']],
    ];
    $form['location']['header']['title'] = [
      '#markup' => '<h2 class="mel-form-title">' . t('Location') . '</h2>',
    ];
    $form['location']['content'] = [
      '#type' => 'container',
      '#attributes' => ['class' => ['mel-form-content']],
    ];

    if (isset($form['field_venue_name'])) {
      $form['location']['content']['field_venue_name'] = $form['field_venue_name'];
      unset($form['field_venue_name']);
    }
    if (isset($form['field_location'])) {
      // Set default country to Australia and hide it
      if (isset($form['field_location']['widget'][0]['address']['country_code'])) {
        $form['field_location']['widget'][0]['address']['country_code']['#default_value'] = 'AU';
        $form['field_location']['widget'][0]['address']['country_code']['#access'] = FALSE;
      }
      // Ensure all address fields are enabled for manual entry
      if (isset($form['field_location']['widget'][0]['address'])) {
        foreach ($form['field_location']['widget'][0]['address'] as $key => &$element) {
          if (is_array($element) && isset($element['#type'])) {
            $element['#disabled'] = FALSE;
          }
        }
      }
      
      // Change widget to autocomplete if available
      // Note: This requires the form display to use myeventlane_location_address_autocomplete
      // For now, we'll ensure the library is attached so autocomplete works if widget supports it
      
      $form['location']['content']['field_location'] = $form['field_location'];
      unset($form['field_location']);
    }
  }

  private function buildBookingConfig(array &$form, FormStateInterface $form_state): void {
    $form['booking_config'] = [
      '#type' => 'container',
      '#attributes' => ['class' => ['mel-form-card', 'mel-form-card-highlight']],
      '#weight' => -7,
    ];
    $form['booking_config']['header'] = [
      '#type' => 'container',
      '#attributes' => ['class' => ['mel-form-header']],
    ];
    $form['booking_config']['header']['title'] = [
      '#markup' => '<h2 class="mel-form-title">' . t('Booking Configuration') . '</h2>',
    ];
    $form['booking_config']['content'] = [
      '#type' => 'container',
      '#attributes' => ['class' => ['mel-form-content']],
    ];

    // STEP 1: Move field_event_type FIRST - before any other fields
    if (isset($form['field_event_type'])) {
      // Remove ALL existing states/conditional_fields
      unset($form['field_event_type']['#states']);
      if (isset($form['field_event_type']['widget'])) {
        unset($form['field_event_type']['widget']['#states']);
        // Also clear from widget[0] if it exists
        if (isset($form['field_event_type']['widget'][0])) {
          unset($form['field_event_type']['widget'][0]['#states']);
        }
      }
      
      // Force it to be first
      $form['field_event_type']['#weight'] = -10000;
      if (isset($form['field_event_type']['widget'])) {
        $form['field_event_type']['widget']['#weight'] = -10000;
      }
      
      // Move it
      $form['booking_config']['content']['field_event_type'] = $form['field_event_type'];
      unset($form['field_event_type']);
    }

    // STEP 2: Build conditional containers with proper #states
    // Use the exact selector that options_select generates
    $selector = ':input[name="field_event_type[0][value]"]';

    // RSVP container
    if (isset($form['field_capacity']) || isset($form['field_rsvp_target'])) {
      $form['booking_config']['content']['rsvp_fields'] = [
        '#type' => 'container',
        '#attributes' => [
          'class' => ['mel-booking-rsvp'],
          'data-booking-type' => 'rsvp',
        ],
        '#weight' => 1,
        '#states' => [
          'visible' => [
            'or' => [
              [$selector => ['value' => 'rsvp']],
              [$selector => ['value' => 'both']],
            ],
          ],
        ],
      ];
      
      if (isset($form['field_capacity'])) {
        unset($form['field_capacity']['#states']);
        $form['field_capacity']['#required'] = FALSE;
        $form['field_capacity']['#weight'] = 1;
        $form['booking_config']['content']['rsvp_fields']['field_capacity'] = $form['field_capacity'];
        unset($form['field_capacity']);
      }
      
      if (isset($form['field_rsvp_target'])) {
        unset($form['field_rsvp_target']['#states']);
        $form['field_rsvp_target']['#required'] = FALSE;
        $form['field_rsvp_target']['#weight'] = 2;
        $form['booking_config']['content']['rsvp_fields']['field_rsvp_target'] = $form['field_rsvp_target'];
        unset($form['field_rsvp_target']);
      }
    }

    // Paid container
    if (isset($form['field_product_target']) || isset($form['field_ticket_types'])) {
      $form['booking_config']['content']['paid_fields'] = [
        '#type' => 'container',
        '#attributes' => [
          'class' => ['mel-booking-paid'],
          'data-booking-type' => 'paid',
        ],
        '#weight' => 2,
        '#states' => [
          'visible' => [
            'or' => [
              [$selector => ['value' => 'paid']],
              [$selector => ['value' => 'both']],
            ],
          ],
        ],
      ];
      
      if (isset($form['field_product_target'])) {
        unset($form['field_product_target']['#states']);
        $form['field_product_target']['#required'] = FALSE;
        $form['field_product_target']['#weight'] = 1;
        $form['booking_config']['content']['paid_fields']['field_product_target'] = $form['field_product_target'];
        unset($form['field_product_target']);
      }
      
      if (isset($form['field_ticket_types'])) {
        unset($form['field_ticket_types']['#states']);
        $form['field_ticket_types']['#required'] = FALSE;
        $form['field_ticket_types']['#weight'] = 2;
        $form['booking_config']['content']['paid_fields']['field_ticket_types'] = $form['field_ticket_types'];
        unset($form['field_ticket_types']);
      }
    }

    // External container
    if (isset($form['field_external_url'])) {
      unset($form['field_external_url']['#states']);
      $form['booking_config']['content']['external_fields'] = [
        '#type' => 'container',
        '#attributes' => [
          'class' => ['mel-booking-external'],
          'data-booking-type' => 'external',
        ],
        '#weight' => 3,
        '#states' => [
          'visible' => [
            [$selector => ['value' => 'external']],
          ],
        ],
        'field_external_url' => $form['field_external_url'],
      ];
      unset($form['field_external_url']);
    }
  }

  private function buildVisibility(array &$form, FormStateInterface $form_state): void {
    $form['visibility'] = [
      '#type' => 'container',
      '#attributes' => ['class' => ['mel-form-card']],
      '#weight' => -6,
    ];
    $form['visibility']['header'] = [
      '#type' => 'container',
      '#attributes' => ['class' => ['mel-form-header']],
    ];
    $form['visibility']['header']['title'] = [
      '#markup' => '<h2 class="mel-form-title">' . t('Visibility & Promotion') . '</h2>',
    ];
    $form['visibility']['content'] = [
      '#type' => 'container',
      '#attributes' => ['class' => ['mel-form-content']],
    ];

    $fields = ['field_category', 'field_event_categories', 'field_tags', 'field_accessibility', 'field_event_status', 'status'];
    foreach ($fields as $field_name) {
      if (isset($form[$field_name])) {
        $form['visibility']['content'][$field_name] = $form[$field_name];
        unset($form[$field_name]);
      }
    }
  }

  private function buildAttendeeQuestions(array &$form, FormStateInterface $form_state): void {
    if (!isset($form['field_attendee_questions'])) {
      return;
    }

    $form['attendee_questions'] = [
      '#type' => 'container',
      '#attributes' => ['class' => ['mel-form-card']],
      '#weight' => -5,
    ];
    $form['attendee_questions']['header'] = [
      '#type' => 'container',
      '#attributes' => ['class' => ['mel-form-header']],
    ];
    $form['attendee_questions']['header']['title'] = [
      '#markup' => '<h2 class="mel-form-title">' . t('Additional Questions') . '</h2>',
    ];
    $form['attendee_questions']['content'] = [
      '#type' => 'container',
      '#attributes' => ['class' => ['mel-form-content']],
    ];

    $form['field_attendee_questions']['#required'] = FALSE;
    $form['attendee_questions']['content']['field_attendee_questions'] = $form['field_attendee_questions'];
    unset($form['field_attendee_questions']);
  }

  private function buildStickyFooter(array &$form, FormStateInterface $form_state, NodeInterface $node, bool $is_new): void {
    if (isset($form['actions'])) {
      $form['actions']['#attributes']['class'][] = 'mel-form-footer';

      if (isset($form['actions']['submit'])) {
        $form['actions']['submit']['#value'] = $is_new ? t('Publish event') : t('Save changes');
        $form['actions']['submit']['#attributes']['class'][] = 'mel-btn-primary';
      }

      $form['actions']['save_draft'] = [
        '#type' => 'submit',
        '#value' => t('Save draft'),
        '#weight' => -10,
        '#submit' => ['_myeventlane_event_save_draft'],
        '#attributes' => ['class' => ['mel-btn-secondary']],
        '#limit_validation_errors' => [],
      ];
    }
  }

  private function getCurrentUserVendorId(): ?int {
    $uid = (int) $this->currentUser->id();
    if ($uid === 0) {
      return NULL;
    }

    $vendor_ids = $this->entityTypeManager->getStorage('myeventlane_vendor')
      ->getQuery()
      ->accessCheck(FALSE)
      ->condition('uid', $uid)
      ->range(0, 1)
      ->execute();

    return !empty($vendor_ids) ? (int) reset($vendor_ids) : NULL;
  }

  private function getCurrentUserStoreId(): ?int {
    $vendor_id = $this->getCurrentUserVendorId();
    if (!$vendor_id) {
      return NULL;
    }

    $vendor = $this->entityTypeManager->getStorage('myeventlane_vendor')->load($vendor_id);
    if (!$vendor || !$vendor->hasField('field_vendor_store') || $vendor->get('field_vendor_store')->isEmpty()) {
      return NULL;
    }

    $store = $vendor->get('field_vendor_store')->entity;
    return $store ? (int) $store->id() : NULL;
  }

}
